// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
// Edited 2015-05-30, SV.

#include <Rcpp.h>

using namespace Rcpp;

// guts_engine
void guts_engine(Rcpp::List gobj, NumericVector par);
RcppExport SEXP GUTS_guts_engine(SEXP gobjSEXP, SEXP parSEXP) {
	BEGIN_RCPP
		Rcpp::RNGScope __rngScope;
		Rcpp::traits::input_parameter< Rcpp::List >::type gobj(gobjSEXP);
		Rcpp::traits::input_parameter< NumericVector >::type par(parSEXP);
		guts_engine(gobj, par);
		return R_NilValue;
	END_RCPP
}
