# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

guts_calc_loglikelihood <- function(gobj, pars) {
    invisible(.Call('GUTS_guts_calc_loglikelihood', PACKAGE = 'GUTS', gobj, pars))
}

