// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// guts_calc_loglikelihood
void guts_calc_loglikelihood(Rcpp::List gobj, NumericVector pars);
RcppExport SEXP GUTS_guts_calc_loglikelihood(SEXP gobjSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type gobj(gobjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    guts_calc_loglikelihood(gobj, pars);
    return R_NilValue;
END_RCPP
}
